### PR TITLE
fix: Limit Recoverable Errors to prevent indefinite data staleness

### LINKED ISSUE #785: Observed recoverable stream error 503 failed to connect to all addresses
From @sls-cat comment:
#504 
Is there any hints as to what causes this?  Having an application go into infinite error scroll like this is not helpful.  I would except a certain number of reconnect attempts and then failure, instead of an infinite look up reconnect attempts.  This has been attempting reconnects for a week now.

```INFO 2022-04-06 13:11:09 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 failed to connect to all addresses
INFO 2022-04-06 13:11:09 streaming_pull_manager.py:1030 Observed recoverable stream error 503 failed to connect to all addresses
INFO 2022-04-06 13:11:09 bidi.py:486 Re-established stream
INFO 2022-04-06 13:12:01 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-04-06 13:12:01 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-04-06 13:12:01 bidi.py:486 Re-established stream
INFO 2022-04-06 13:14:32 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-04-06 13:14:32 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-04-06 13:14:32 bidi.py:486 Re-established stream
INFO 2022-04-06 13:15:32 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-04-06 13:15:32 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-04-06 13:15:32 bidi.py:486 Re-established stream
INFO 2022-04-06 13:16:42 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:16:42 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:16:42 bidi.py:486 Re-established stream
INFO 2022-04-06 13:18:02 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-04-06 13:18:02 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-04-06 13:18:02 bidi.py:486 Re-established stream
INFO 2022-04-06 13:19:31 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-04-06 13:19:31 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-04-06 13:19:32 bidi.py:486 Re-established stream
INFO 2022-04-06 13:20:57 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:20:57 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:20:57 bidi.py:486 Re-established stream
INFO 2022-04-06 13:21:50 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:21:50 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:21:50 bidi.py:486 Re-established stream
INFO 2022-04-06 13:22:55 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:22:55 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:22:55 bidi.py:486 Re-established stream
INFO 2022-04-06 13:24:20 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:24:20 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:24:20 bidi.py:486 Re-established stream
INFO 2022-04-06 13:25:40 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 failed to connect to all addresses
INFO 2022-04-06 13:25:40 streaming_pull_manager.py:1030 Observed recoverable stream error 503 failed to connect to all addresses
INFO 2022-04-06 13:25:40 bidi.py:486 Re-established stream
INFO 2022-04-06 13:26:53 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:26:53 streaming_pull_manager.py:1030 Observed recoverable stream error 503 keepalive watchdog timeout
INFO 2022-04-06 13:26:53 bidi.py:486 Re-established stream```

```astroid==2.9.3
attrs==21.4.0
box-pyvault==1.7.0
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.0.4
coverage[toml]==6.2
google-api-core[grpc]==2.7.1
google-api-python-client==2.41.0
google-auth==2.6.0
google-auth-httplib2==0.1.0
google-cloud-access-context-manager==0.1.10
google-cloud-asset==3.8.1
google-cloud-bigquery==2.34.2
google-cloud-core==2.2.3
google-cloud-org-policy==1.3.1
google-cloud-os-config==1.11.1
google-cloud-pubsub==2.11.0
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos[grpc]==1.56.0
grpc-google-iam-v1==0.12.3
grpcio==1.44.0
grpcio-status==1.44.0
httplib2==0.20.4
hvac==0.11.2
idna==3.3
importlib-metadata==4.8.3
iniconfig==1.1.1
isort==5.10.1
lazy-object-proxy==1.7.1
mccabe==0.6.1
mock==4.0.3
packaging==21.3
platformdirs==2.4.0
pluggy==1.0.0
proto-plus==1.20.3
protobuf==3.19.4
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pylint==2.12.2
pyparsing==3.0.7
pytest==7.0.1
pytest-cov==3.0.0
python-dateutil==2.8.2
requests==2.27.1
rsa==4.8
six==1.16.0
toml==0.10.2
tomli==1.2.3
typed-ast==1.5.2
typing-extensions==4.1.1
uritemplate==4.1.1
urllib3==1.26.9
wrapt==1.13.3
zipp==3.6.0
```

I see it started with this, which appears to have some issues in the SDK:

```WARNING 2022-03-31 23:24:15 processor.py:202 PUBSUB_ACK_OK (cb_count 1963 delivery_attempt None publish_time 2022-04-01 06:23:55.058000+00:0
0 message_size 28611 ack_id U0RQBhYsXUZIUTcZCGhRDk9eIz81IChFEgggagktQlgeDwdcXHUHUQweJChjcztTQAdWT1F3XlwdB2h0bG251Ke7RF9BcWlaEQYETVF_W1keDG1V
WF3zkbe42uXDQ3BmK7-H7_FIf7qtx9ZvZiA9WxJLLD5-NSNFQV5AEkw-FkRJUytDCypYEU4EISE-MD5F) at 2022-03-31 23:24:15.
INFO 2022-03-31 23:24:43 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 Connection timed out
INFO 2022-03-31 23:24:43 streaming_pull_manager.py:1030 Observed recoverable stream error 503 Connection timed out
INFO 2022-03-31 23:24:43 bidi.py:486 Re-established stream
INFO 2022-03-31 23:26:03 streaming_pull_manager.py:1052 Observed non-terminating stream error 503 failed to connect to all addresses
ERROR 2022-03-31 23:26:03 helper_threads.py:120 Error in queue callback worker: 'NoneType' object has no attribute 'set_exception'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1648794363.414576733","description":"Failed to pick subchannel","file":"src/core/ext/filters/clie
nt_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1648794363.414575083","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 589, in send_unary_ack
    self._client.acknowledge(subscription=self._subscription, ack_ids=ack_ids)
  File "/usr/local/lib/python3.6/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1201, in acknowledge
    request, retry=retry, timeout=timeout, metadata=metadata,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py", line 118, in __call__
    self._callback(items)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 159, in dispatch_callback
    self.ack(ack_requests)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 192, in ack
    ack_reqs_dict=ack_reqs_dict,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 604, in send_unary_ack
    _process_requests(status, ack_reqs_dict, None)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 204, in _process_requests
    future.set_exception(exc)
AttributeError: 'NoneType' object has no attribute 'set_exception'
INFO 2022-03-31 23:26:03 streaming_pull_manager.py:1030 Observed recoverable stream error 503 failed to connect to all addresses
ERROR 2022-03-31 23:26:03 bidi.py:673 Thread-ConsumeBidirectionalStream caught unexpected exception 'NoneType' object has no attribute 'set_exception' and will exit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1648794363.414594016","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1648794363.414592880","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 644, in send_unary_modack
    ack_deadline_seconds=deadline,
  File "/usr/local/lib/python3.6/site-packages/google/pubsub_v1/services/subscriber/client.py", line 1098, in modify_ack_deadline
    request, retry=retry, timeout=timeout, metadata=metadata,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 986, in _on_response
    self._send_lease_modacks(ack_id_gen, self.ack_deadline)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 932, in _send_lease_modacks
    self._dispatcher.modify_ack_deadline(items)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py", line 295, in modify_ack_deadline
    ack_reqs_dict=ack_reqs_dict,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 660, in send_unary_modack
    _process_requests(status, ack_reqs_dict, None)
  File "/usr/local/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 204, in _process_requests
    future.set_exception(exc)
AttributeError: 'NoneType' object has no attribute 'set_exception'
INFO 2022-03-31 23:26:03 bidi.py:486 Re-established stream
INFO 2022-03-31 23:26:03 bidi.py:676 Thread-ConsumeBidirectionalStream exiting

_Originally posted by @sls-cat in https://github.com/googleapis/python-pubsub/issues/504#issuecomment-1090767051_

### PR DESCRIPTION
**Pull request by PeteRager**
In the current design, the stream manager automatically recovers from transient errors.  The side effect is that if the transient error becomes non-transient (e.g. persists for longer than the API client can tolerate); there is no notification.  This causes the client to believe the subscription is up-to-date; whereas, it could have been disconnected for days.

The proposed change; is to allow the client to specify the maximum number of consecutive recoverable errors that it is willing to tolerate before declaring the subscription failed.  This change is accomplished by adding an additional parameter to the client.

---

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #785  🦕

### CODE REVIEW

**Comment by PeteRager** [comment]
Let me know the next steps and feedback on the approach, happy to rework based on your suggestions.

**Comment by allenporter** [comment]
Some of the other APIs take a `google.api_core.retry.Retry` to allow customization of retry behavior, which might fit naturally here and allow other types of customizations. Would that work here?

(I'm not an expert in this code base and have no sway in this review, just thinking about how to make it more likely to be accepted)

**Comment by PeteRager** [comment]
> Some of the other APIs take a `google.api_core.retry.Retry` to allow customization of retry behavior, which might fit naturally here and allow other types of customizations. Would that work here?
> 
I did consider that and it could be a good approach.  Since there was already a retry object that is faulty (nothing should retry forever), i thought that adding a parameter to control its behavior was a simple way to solve.  Either way, I’m not tied to my specific implementation.  Just want to get the problem solved, so i can then work on our downstream issue.

**Comment by allenporter** [comment]
I'm not sure I agree that retrying forever is a always a problem for a subscriber API, and kind of matches my expectations for default behavior.

**Comment by PeteRager** [comment]
Resolved conflicts from main

**Comment by PeteRager** [comment]
What are the next steps on this item?

**Comment by PeteRager** [comment]
Bump

**Comment by acocuzzo** [comment]
@PeteRager Thanks for your PR. When we make changes to the Pub/Sub libraries, we try to coordinate these changes across libraries for consistent behavior, so this PR is unlikely to be merged until the library owners have reached a consensus that the changes should be made across libraries.
Presumably after this type of retryable error, the user would simply try to recreate the client, and encounter the same error.
We are considering implementing logic depending on whether the connection has ever been successful (for instance, limiting retries on start up, but retrying forever on reconnection).
For your specific use case,  I'm wondering if your "staleness" issue could be solved by checking the age of the last processed message. Is this a possible fix for your specific case?

**Comment by allenporter** [comment]
The use case is for listening to nest API pubsub events, where the user is not controlling the publisher side.

IMO my take is the minimum needed for this use case is to understand if the pubsub feed is currently unhealthy, and the client can manage the rest. (E.g. cancellation, determining if it was ever healthy.) However I realize that may not be a fully complete API, just wanted to clarify the use case for library owners to understand.

**Comment by acocuzzo** [comment]
Regarding the fix for the use case, could the age of the received messages be checked on the subscribe side? Aka the age of the last received message > n, the information may be stale?

And yes, I understand. Thanks for your changes, and your patience. This is something being discussed among client library owners for all languages, and the suggestions are definitely appreciated.

**Comment by acocuzzo** [comment]
Marking this PR as do not merge as the changes are dependent on cross-language library changes.

**Comment by allenporter** [comment]
I guess the challenge is there isn't a guarantee for how often messages are published. E.g. nobody pressed my doorbell so no publishing happens and that is normal.

Thanks

**Comment by PeteRager** [comment]
> I guess the challenge is there isn't a guarantee for how often messages are published. E.g. nobody pressed my doorbell so no publishing happens and that is normal.
> 

Correct, and as a result we’d strike down the connection a lot and confuse users with “timeout” messages.

When the application becomes partitioned from the cloud publisher the application needs a notification that the connection is unhealthy.  Otherwise building on Alan’s example, when someone does press the doorbell no message is received because the connection is in an unhealthy state. The net affect is the application is viewed as unreliable and Alan and I have unhappy users.

I understand the need to have a consistent API across the languages you support.

Minimum Need
- don’t perform retries, just notify application that connection has failed.  The application retries.

Better solve
- automatically perform some limited # of retries (controllable by application, and could be zero to obtain minimum behavior), above this limit notify the application that the connection has failed.  The application retries.   This PR functionally does this.

**Pull request closed without merging**
