### PR TITLE
samples: add samples from pubsub/cloud-client

### LINKED ISSUE #136: Add pubsub/cloud-client samples from the samples repo
A transition to the new code generator (#131) requires the code samples to be moved from the common samples repo to here.

### PR DESCRIPTION
**Pull request by plamut**
Closes #136.
Towards #131.

Samples from https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/pubsub/cloud-client

---
> **IMPORTANT:** When merging, use the **rebase and merge** option to preserve the samples commit history!
---

This PR is a follow-up to #134 that was merged by squashing all the commits from the samples repo. The first commit reverts the (squashed) merged changes, while the rest are the commits from the original PR rebased onto that reversal commit. The PR thus also replaces #141.

### CODE REVIEW

**Comment by plamut** [comment]
Also addressed the [feedback](https://github.com/googleapis/python-pubsub/pull/134#pullrequestreview-443764657) by @sgerrand, cleaned up a few things in the samples.

Not entirely sure what the missing `quickstart.py` should contain, thus replaced it with two quickstart sections for Publisher and Subscriber (better than a missing file).

**Comment by sgerrand** [comment]
Thanks @plamut!

**Comment by plamut** [comment]
Somebody please also confirm that CLAs are in order :)

**Comment by busunkim96** [comment]
Samples are being moved from GoogleCloudPlatform/python-docs-samples (CLAs were already obtained there).

**Pull request merged**
