### PR TITLE
docs: Changed Python 2 EOL notice from future to present

### PR DESCRIPTION
**Pull request by OrBin**
The library has a Python 2 EOL notice in the docs.
Since the set date has passed, I've changed the phrasing from future to present.

### CODE REVIEW

**Comment by plamut** [comment]
@OrBin Thanks for the pull request, although the library is currently still compatible with Python 2, because the last Python 2 update actually happened in late April 2020 to include the fixes done before the end of 2019.

@busunkim96 What should be the exact wording across libraries? Technically, we still support Python 2 and we have not yet made a release that is not compatible with it, at least not in PubSub.

Thanks!

**Comment by busunkim96** [comment]
I'd prefer to keep the current wording and change it when the library officially stops working with 2. Open to other ideas though.

**Comment by plamut** [comment]
While far from ideal, the old wording describes the current state of affairs slightly better, IMO.

To me it looks like a neglected future notice added before 2020, while using the past tense would actually make the claim about dropped Python 2 support stronger - which has not come into effect yet.

Let's put this PR on hold until the facts match the new wording better. :)

**Comment by OrBin** [comment]
Sounds good to me. 
Another option is rewording to fit the current state, but I guess that's OK too.
Do you expect to release a new version soon?

**Comment by plamut** [comment]
@OrBin From what I heard, some of the Google Cloud Python client libraries will start dropping Python 2.7 support in the near future, though no concrete day for PubSub yet.

As for the next PubSub release - one minor release was made yesterday, and the next one will likely follow some time after publisher flow control is added (PR #96). The latter will still work with Python 2.7.

**Comment by plamut** [comment]
Closing in favor of #158, the latter will make the exact changes that are consistent with docs changes in other libraries.

**Pull request closed without merging**
