### PR TITLE
chore: migrate default branch to main

### LINKED ISSUE #478: Migrate from master to main branch
As part of the umbrella issue googleapis/google-cloud-python#10579, we need to switch the default branch from `master` to `main`. Also, all occurrences of `master` should be renamed to `main` (except in cases where URLs could be broken, because the migration has not happened yet).

### PR DESCRIPTION
**Pull request by plamut**
Fixes #478.

### CODE REVIEW

**Review by tseaver — COMMENTED** [review]
No replacments in `owlbot.py` to preserve these changes?

**Comment by plamut** [comment]
I'm starting to suspect that the script I used has bugs, as some of the files are autogenerated (IIRC)...

**Comment by tseaver** [comment]
@plamut it looks like the `Owlbot Post Processor` check isn't configured for this repo, either.  @parthea can you please investigate?

**Comment by plamut** [comment]
Putting this on hold until we investigate.

**Comment by parthea** [comment]
I've added the `owlbot:run` label. Usually this step isn't required. For example, see https://github.com/googleapis/python-datastream/pull/17

**Comment by parthea** [comment]
Hi @plamut, please let me know if you have any questions.

**Review by tseaver — APPROVED** [review]

**Pull request merged**
