### PR TITLE
docs: add type annotations to codebase

### LINKED ISSUE #500: Add type annotations to the codebase
Just as to https://github.com/googleapis/python-pubsub/issues/264 added type annotations to samples, this issue is about adding type hints to the library code itself.

Should wait until CI type checks are added in https://github.com/googleapis/python-pubsub/issues/477.

### PR DESCRIPTION
**Pull request by plamut**
Closes #500.

**PR checklist:**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by plamut** [comment]
NOTE: `py.typed` file ([PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)) marker was intentionally **not** added, as this could break the workflows of users that use `mypy` for type checks. This [happened](https://github.com/googleapis/python-bigquery/pull/988) in BigQuery, for example.

We will thus likely add `py.typed` once we know for sure that `mypy` is happy with our type annotations.

**Review by anguillanneuf — APPROVED** [review]
This is great! Thanks a lot!

**Review by pradn — APPROVED** [review]
Looks good, thanks!

**Comment by plamut** [comment]
Thank you both for the reviews!

**Pull request merged**
