### PR TITLE
docs: fix get topic_path in subscriber sample

### LINKED ISSUE #209: SubscriberClient no longer has 'topic_path' method, but documentation still makes references to it.
After the update to library version 2.1.0, the SubscriberClient no longer has a 'topic_path' method. I'm assuming that was intentional, but the documentation still makes reference to it.

Here is a link to one such instance in the documentation:
https://googleapis.dev/python/pubsub/latest/subscriber/index.html#creating-a-subscription

### PR DESCRIPTION
**Pull request by ryanyuan**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #209  🦕

### CODE REVIEW

**Review by marjohkan — COMMENTED** [review]
Are you meaning to create an instance of pubsub.SubscriberClient and name the variable "publisher"?
Line 40:
` # publisher = pubsub.SubscriberClient()`

**Comment by ryanyuan** [comment]
@marjohkan It should be 'publisher = pubsub.PublisherClient()'. My bad, copy/paste error.

**Comment by ryanyuan** [comment]
@plamut I just accidentally removed googleapis/api-pubsub from reviewers.

**Review by plamut — APPROVED** [review]
Looks good, thanks for catching and fixing this!

**Comment by plamut** [comment]
"Stream removed" flakiness caused the Python3.7 samples check to fail.

**Pull request merged**
