### PR TITLE
fix: Upgrade proto-plus to support Python 3.13

### LINKED ISSUE #1275: Not compatible Python 3.13.0 ?
#### Environment details

  - OS type and version: Version WSL : 2.3.24.0
  - Python version: 3.13.0
  - pip version: 24.2
  - `google-cloud-pubsub` version: 2.26.0

#### Steps to reproduce

  1. Upgrade to Python 3.13.0
  2. Just load library `from google.cloud import pubsub_v1`

#### Code example

```python
from google.cloud import pubsub_v1

print("Hello World")
```

#### Stack trace
```
Traceback (most recent call last):
  File "./src/test.py", line 1, in <module>
    from google.cloud import pubsub_v1
  File "./.venv/lib/python3.13/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "./.venv/lib/python3.13/site-packages/google/cloud/pubsub_v1/types.py", line 39, in <module>
    from google.pubsub_v1.types import pubsub as pubsub_gapic_types
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/__init__.py", line 21, in <module>
    from .services.publisher import PublisherClient
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/services/publisher/__init__.py", line 16, in <module>
    from .client import PublisherClient
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/services/publisher/client.py", line 57, in <module>
    from google.pubsub_v1.services.publisher import pagers
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/services/publisher/pagers.py", line 40, in <module>
    from google.pubsub_v1.types import pubsub
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/types/__init__.py", line 18, in <module>
    from .pubsub import (
    ...<48 lines>...
    )
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/types/pubsub.py", line 25, in <module>
    from google.pubsub_v1.types import schema as gp_schema
  File "./.venv/lib/python3.13/site-packages/google/pubsub_v1/types/schema.py", line 507, in <module>
    class ValidateMessageResponse(proto.Message):
        r"""Response for the ``ValidateMessage`` method. Empty for now."""
  File "./.venv/lib/python3.13/site-packages/proto/message.py", line 279, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.pubsub.v1.__firstlineno__'

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by dangarmol**
This change should fix issue #1275. A similar change has been proposed for https://github.com/googleapis/python-api-core/pull/740.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-pubsub/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1275 🦕

### CODE REVIEW

**Review by parthea — APPROVED** [review]

**Comment by dangarmol** [comment]
That's an interesting failure, I can't really see how it's related to my changes though 🤔

Maybe it's time to drop Python 3.7 and execute the test suite in 3.13 as well?

**Comment by mukund-ananthu** [comment]
>Maybe it's time to drop Python 3.7

Dropping Python 3.7 from presubmits implies that any issues / regressions in Python 3.7 would not be caught. Any issues / regressions in Python 3.7 would be considered a backward incompatible change. Backward incompatible changes are mostly discouraged(unless there is an exceptional reason - this isn't one of them)

**Comment by parthea** [comment]
Wait for https://github.com/googleapis/synthtool/pull/2031

**Comment by mukund-ananthu** [comment]
@parthea :

### Pip Freeze:

```
cachetools==5.5.0
certifi==2024.8.30
charset-normalizer==3.4.0
Deprecated==1.2.14
google-api-core==2.22.0
google-auth==2.35.0
google-cloud-pubsub @ file:///workspaces/python-pubsub
googleapis-common-protos==1.65.0
grpc-google-iam-v1==0.13.1
grpcio==1.67.1
grpcio-status==1.67.1
idna==3.10
importlib_metadata==8.4.0
iniconfig==2.0.0
opentelemetry-api==1.27.0
opentelemetry-sdk==1.27.0
opentelemetry-semantic-conventions==0.48b0
packaging==24.1
pluggy==1.5.0
proto-plus==1.25.0
protobuf==5.28.3
pyasn1==0.6.1
pyasn1_modules==0.4.1
pytest==8.3.3
pytest-asyncio==0.24.0
requests==2.32.3
rsa==4.9
typing_extensions==4.12.2
urllib3==2.2.3
wrapt==1.16.0
zipp==3.20.2
```
### Repro Code:

```python
from google.cloud import pubsub_v1

print("Hello World")
```

Confirmed that the repro code works for python version = 3.11:

```
 $ python3 repro.py 
Hello World
```

### Setup .py  file with the proto-plus dependency updated

```
dependencies = [
    "grpcio >= 1.51.3, < 2.0dev",  # https://github.com/googleapis/python-pubsub/issues/609
    # google-api-core >= 1.34.0 is allowed in order to support google-api-core 1.x
    "google-auth >= 2.14.1, <3.0.0dev",
    "google-api-core[grpc] >= 1.34.0, <3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*",
    "proto-plus >= 1.22.0, < 2.0.0dev",
    "proto-plus >= 1.22.2, < 2.0.0dev; python_version >= '3.11'",
    "proto-plus >= 1.25.0, < 2.0.0dev; python_version >= '3.13'",
    "protobuf>=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5",
    "grpc-google-iam-v1 >= 0.12.4, < 1.0.0dev",
    "grpcio-status >= 1.33.2",
    "opentelemetry-api <= 1.22.0; python_version<='3.7'",
    "opentelemetry-api >= 1.27.0; python_version>='3.8'",
    "opentelemetry-sdk <= 1.22.0; python_version<='3.7'",
    "opentelemetry-sdk >= 1.27.0; python_version>='3.8'",
]
```

I still get an error with the above change:

```
$ python3.13 repro.py 
Traceback (most recent call last):
  File "/workspaces/python-pubsub/repro.py", line 1, in <module>
    from google.cloud import pubsub_v1
  File "/workspaces/python-pubsub/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/workspaces/python-pubsub/google/cloud/pubsub_v1/types.py", line 24, in <module>
    import proto  # type: ignore
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'proto'
```

So, this change does not seem to resolve the issue, although I see that it was applied as a fix for the other client libraries. Wanted to check if you know why this might be happening?

**Comment by mukund-ananthu** [comment]
Issue solved with https://github.com/googleapis/python-pubsub/pull/1303 .Closing this.

**Pull request closed without merging**
